services:
  app:
    build: .
    ports:
      - "9878:9878"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=rt_rw_db
      - PORT=9878
      - SESSION_SECRET=rahasia_super_aman
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rt_rw_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data:
